### PR TITLE
Replace x86 builds with arm64 on all platforms

### LINKED ISSUE #287: Produce builds for arm64
There don't seem to be any builds for arm64/aarch64 which would be nice to have. Current state seems a bit odd as Gauge itself has arm64 builds. :-)

### PR DESCRIPTION
**Pull request by chadlwilson**
- Fixes #287 
- upgrades golang to latest version (1.19.5). 1.13 is ancient and cannot build for arm64 on most platforms. Newer versions have dropped 32-bit support for some platforms as well so dropped here as well. I don't see why building for 32-bit platforms should be necessary now.
- Corrects builds/tests to work against modern Go (most have a module, can't have two `main()` files in same package)
- Upgrades github actions to latest versions
- Runs against
  - Ruby 2.7 (Ruby 2.6 is EOL, 2.7 is EOL in 2 months...)
  - Java 17 LTS (Java 12 was a non LTS build and is years past EOL)

Not sure I know exactly what I am doing here, but hoping the tests give confidence.... :-)

### CODE REVIEW

**Review by sriv — APPROVED** [review]

**Comment by sriv** [comment]
As you have seen, various deps are ancient here, including the actions. Thanks for the cleanup Chad!

**Comment by chadlwilson** [comment]
Hi @sriv - I'm just trying to get the tests to pass on my branch builds right now. Just Windows lsps remaining (seems to be trying to clone `chadlwilson/master` rather than the PR branch for some reason, so working around that :-)

**Comment by chadlwilson** [comment]
My root motivation is to try and get https://github.com/gocd/gocd/issues/8544 done - easiest path is to be able to validate such builds is to run https://github.com/gocd/ruby-functional-tests on arm64 directly and be able to test built docker images on linux/arm64 which is dependent on gauge/gauge-ruby. Tried doing so by emulation/qemu, but that seems to be leading to a world of pain :-)

Although I also have problems running the gauge-ruby functional tests locally now since I have an M1 Macbook, so would be good to have `darwin/arm64` working independent of my attempts to produce official arm64 gocd distributions

**Comment by sriv** [comment]
Not at my computer at the mo. But apart from the launcher (which is gauge-ruby.go) do you see any other dep that is platform dependant? Not sure if we have any native gem here.

If it is only the launcher, I can try to see if we can get rid of that and put something more idiomatic to ruby world

**Comment by chadlwilson** [comment]
@sriv Sure, no worries - not asking for any immediate help 🙏

At the moment building the native executables doesn't seem to be the main challenge - that was the easy bit, it's getting all the Ruby-related dependencies and tests to work, and things that are linked to specific (now EOL) Ruby versions.

**Comment by chadlwilson** [comment]
I've eventually got the `lsp` tests working on Windows by removing the debugger support completely due to
1.  `Errno::ENOENT: No such file or directory @ realpath_rec - D:/a/gauge-ruby/gauge-ruby/gauge-lsp-tests/data/vendor/ruby/2.7.0/gems/debase-ruby_core_source-3.2.0/lib` errors
2. inability to install `debase` on Ruby 3.1/linux due to it trying to compile native extensions from source), and non-beta versions having other errors.

Now the FTs are just hanging on Windows so I guess something else is wrong. https://github.com/chadlwilson/gauge-ruby/actions/runs/3973795156/jobs/6812687808

```
Sat, 21 Jan 2023 08:10:14 GMT Installing required plugins.
Sat, 21 Jan 2023 08:10:15 GMT .....................
Sat, 21 Jan 2023 08:10:15 GMT Successfully installed plugin 'screenshot' version 0.1.0
Sat, 21 Jan 2023 08:10:22 GMT SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Sat, 21 Jan 2023 08:10:22 GMT SLF4J: Defaulting to no-operation (NOP) logger implementation
Sat, 21 Jan 2023 08:10:22 GMT SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sat, 21 Jan 2023 08:10:27 GMT Executing in 2 parallel streams.
Sat, 21 Jan 2023 08:10:27 GMT [runner: 2] # Continue on failure
Sat, 21 Jan 2023 08:10:27 GMT [runner: 1] # Continue on failure in concepts
Sat, 21 Jan 2023 08:10:27 GMT [runner: 1]   ## Continue on failure in a concept step
Sat, 21 Jan 2023 08:10:27 GMT [runner: 2]   ## Continue execution on any error/exception in "Continue on Failure" step
Sat, 21 Jan 2023 08:10:43 GMT > Task :rubyFT

.... hang
```

I don't really understand what it's doing as the `gauge.log` doesn't seem to mention anything about ruby and seems to generally be running `gauge-java` stuff.

```
21-01-2023 08:10:26.861 [Gauge] [DEBUG] Validation completed.
21-01-2023 08:10:26.862 [Gauge] [DEBUG] Run started
21-01-2023 08:10:26.862 [Gauge] [DEBUG] Starting Html Report plugin
21-01-2023 08:10:26.881 [html-report] [DEBUG] Setting MaxRecvMsgSize = 1024 MB
21-01-2023 08:10:26.881 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 53531
21-01-2023 08:10:26.882 [Gauge] [DEBUG] Successfully made the connection with plugin with port: 53531
21-01-2023 08:10:26.882 [Gauge] [DEBUG] Starting Xml Report plugin
21-01-2023 08:10:26.898 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 53534
21-01-2023 08:10:26.899 [Gauge] [DEBUG] Successfully made the connection with plugin with port: 53534
21-01-2023 08:10:26.899 [Gauge] [INFO] Executing in 2 parallel streams.
21-01-2023 08:10:26.899 [Gauge] [DEBUG] Using multithreading for parallel execution.
21-01-2023 08:10:26.918 [Gauge] [INFO] # Continue on failure
21-01-2023 08:10:26.918 [Gauge] [INFO] # Continue on failure in concepts
21-01-2023 08:10:27.355 [Gauge] [INFO] ## Continue on failure in a concept step
21-01-2023 08:10:27.368 [Gauge] [DEBUG] * Initialize a project named "continueOnFailure" without example spec

21-01-2023 08:10:27.391 [java] [DEBUG] Executing 'Initialize a project named {} without example spec' using 'class com.thoughtworks.gauge.test.implementation.ProjectInit.projectInitWithoutHelloWorldSpec
21-01-2023 08:10:27.551 [Gauge] [INFO] ## Continue execution on any error/exception in "Continue on Failure" step
21-01-2023 08:10:27.560 [Gauge] [DEBUG] * Initialize a project named "continueOnFailure" without example spec

21-01-2023 08:10:27.564 [java] [DEBUG] Executing 'Initialize a project named {} without example spec' using 'class com.thoughtworks.gauge.test.implementation.ProjectInit.projectInitWithoutHelloWorldSpec
```

**Comment by chadlwilson** [comment]
Hi @sriv - any chance you'd be interested to help me figure out what is wrong with the build/test system so I can get ARM builds for gauge-ruby through?

GoCD's functional tests rely on gauge-ruby and I'd like to get them running on arm64 so I can drive testing of arm64 container images natively without QEMU or equivalent :-/

Obviously I can produce custom builds, but would also prefer not to do that if I can avoid it.

**Comment by chadlwilson** [comment]
FWIW, I cut a manual release which works for my short-term purposes (on `linux.arm64`) at https://github.com/chadlwilson/gauge-ruby/releases/tag/v0.5.5-chadlwilson. Seems to interoperate OK with the `0.5.4` ruby Gem.

Would much prefer to not have to use a fork though: https://github.com/gocd-contrib/gocd-oss-cookbooks/blob/aea090d8c2389b5dbc395a544324d0462df9c398/provision/common.sh#L101-L105

**Comment by chadlwilson** [comment]
This seems stuck, so will re-open a clean PR after getting everything passing.

**Pull request closed without merging**
